spring.application.name=gym-tracker
tracker.spreadsheet-id=${GOOGLE_SHEETS_SPREADSHEET_ID}
spring.datasource.url=jdbc:postgresql://localhost:5432/gym_tracker
spring.datasource.username=gym_user
spring.datasource.password=gym_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
tracker.current-user-email=Bob@example.com