spring.application.name=gym-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/gym_tracker
spring.datasource.username=gym_user
spring.datasource.password=gym_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
tracker.current-user-email=bob@example.com
spring.jpa.open-in-view=false