CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE daily_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    calories INTEGER NOT NULL CHECK (calories > 0),
    protein_g NUMERIC(6, 2) NOT NULL CHECK (protein_g >= 0),
    carbs_g NUMERIC(6, 2) NOT NULL CHECK (carbs_g >= 0),
    fat_g NUMERIC(6, 2) NOT NULL CHECK (fat_g >= 0),
    effective_from DATE NOT NULL,
    UNIQUE (user_id, effective_from)
);

CREATE TABLE nutrition_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    log_date DATE NOT NULL,
    day_number INTEGER NOT NULL CHECK (day_number > 0),
    calories INTEGER NOT NULL CHECK (calories >= 0),
    protein_g NUMERIC(6, 2) NOT NULL CHECK (protein_g >= 0),
    carbs_g NUMERIC(6, 2) NOT NULL CHECK (carbs_g >= 0),
    fat_g NUMERIC(6, 2) NOT NULL CHECK (fat_g >= 0),
    weight_kg NUMERIC(5, 2),
    notes VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, log_date)
);

CREATE TABLE workout_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    workout_date DATE NOT NULL,
    day_number INTEGER NOT NULL CHECK (day_number > 0),
    name VARCHAR(100) NOT NULL,
    notes VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, workout_date, name)
);

CREATE TABLE exercise_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_session_id BIGINT NOT NULL
        REFERENCES workout_sessions(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    exercise_order INTEGER NOT NULL CHECK (exercise_order > 0),
    notes VARCHAR(500),
    UNIQUE (workout_session_id, exercise_order)
);

CREATE TABLE exercise_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_log_id BIGINT NOT NULL
        REFERENCES exercise_logs(id) ON DELETE CASCADE,
    set_number INTEGER NOT NULL CHECK (set_number > 0),
    weight_kg NUMERIC(6, 2),
    reps INTEGER NOT NULL CHECK (reps > 0),
    UNIQUE (exercise_log_id, set_number)
);

CREATE INDEX idx_nutrition_logs_date
    ON nutrition_logs(user_id, log_date);

CREATE INDEX idx_workout_sessions_date
    ON workout_sessions(user_id, workout_date);